/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lp1_e5;

import java.io.IOException;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Alert;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author info-chefe
 */
public class Form_Sofa extends javax.swing.JFrame 
{
    

    /**
     * Creates new form Form_Calcado
     */
    public Form_Sofa() throws Exception
    { 
        initComponents();
        PopularJTable();
    }
    
    public void PopularJTable() throws Exception 
    {
        try
        {
            Connection conn = null;
            ResultSet resultadoBanco = null;
            conn = DBConexao.abrirConexao();
            Statement stm = conn.createStatement();
                
            String sql0;
            sql0 = "SELECT * FROM sofa ";
            resultadoBanco = stm.executeQuery(sql0);
         
            DefaultTableModel model =(DefaultTableModel) tbview_Sofa.getModel();
            model.setNumRows(0);

            while(resultadoBanco.next())
            {
                model.addRow(new Object[] 
                { 
                   //retorna os dados da tabela do BD, cada campo e um coluna.
                   resultadoBanco.getString("sofa_id"),
                   resultadoBanco.getString("sofa_modelo"),
                   resultadoBanco.getString("sofa_cor"),
                   resultadoBanco.getString("sofa_tecido"),
                   resultadoBanco.getString("sofa_tamanho"),
                   resultadoBanco.getString("sofa_valor")
                }); 
            } 

        }
       catch (SQLException ex){System.out.println("o erro foi " +ex);}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_sofaCor = new javax.swing.JTextField();
        txt_sofaTamanho = new javax.swing.JTextField();
        txt_sofaValor = new javax.swing.JTextField();
        txt_sofaTecido = new javax.swing.JTextField();
        txt_sofaModelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbview_Sofa = new javax.swing.JTable();
        btn_salvar = new javax.swing.JButton();
        btn_deletar = new javax.swing.JButton();
        txt_sofaPesqModelo = new javax.swing.JTextField();
        txt_sofaPesqCor = new javax.swing.JTextField();
        btn_pesquisar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_sofaId = new javax.swing.JTextField();
        btn_Limpar = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FORMULÁRIO DE SOFÁ");

        txt_sofaValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sofaValorActionPerformed(evt);
            }
        });

        txt_sofaTecido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sofaTecidoActionPerformed(evt);
            }
        });

        jLabel2.setText("MODELO:");

        jLabel3.setText("COR");

        jLabel4.setText("TECIDO:");

        jLabel5.setText("TAMANHO:");

        jLabel6.setText("VALOR:");

        tbview_Sofa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MODELO", "COR", "TECIDO", "TAMANHO", "VALOR"
            }
        ));
        tbview_Sofa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbview_SofaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbview_Sofa);

        btn_salvar.setText("SALVAR");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_deletar.setText("DELETAR");
        btn_deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletarActionPerformed(evt);
            }
        });

        btn_pesquisar.setText("PESQUISAR");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });

        jLabel7.setText("MODELO:");

        jLabel8.setText("COR:");

        jLabel9.setText("PESQUISAR SOFÁ");

        txt_sofaId.setEditable(false);
        txt_sofaId.setText("0");

        btn_Limpar.setText("LIMPAR");
        btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparActionPerformed(evt);
            }
        });

        btn_voltar.setText("VOLTAR");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_sofaId, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_sofaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_sofaTecido, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txt_sofaTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_sofaCor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_sofaValor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btn_Limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_salvar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(jLabel8))
                                .addComponent(jLabel7))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_sofaPesqModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_sofaPesqCor, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(92, 92, 92)
                            .addComponent(btn_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(172, 172, 172)))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_deletar)
                .addGap(227, 227, 227))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(txt_sofaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sofaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sofaCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sofaTecido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_sofaTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_sofaValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel5))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_salvar)
                    .addComponent(btn_Limpar))
                .addGap(146, 146, 146))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_sofaPesqModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_sofaPesqCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18))
                    .addComponent(btn_pesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_deletar)
                    .addComponent(btn_voltar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // TODO add your handling code here:
        String sofa_id = txt_sofaId.getText();
        String sofa_modelo = txt_sofaModelo.getText();
        String sofa_cor = txt_sofaCor.getText();
        String sofa_tecido = txt_sofaTecido.getText();
        String sofa_tamanho = txt_sofaTamanho.getText();
        String sofa_valor = txt_sofaValor.getText();
        
        if(!"0".equals(sofa_id))
        {
            Connection conn = null;
            ResultSet resultadoBanco = null;
                     
            try { conn = DBConexao.abrirConexao();} catch (Exception ex){ Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
            Statement stm = null;
            try { stm = conn.createStatement();} catch (SQLException ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}

            String sql;
            sql = "UPDATE sofa SET "
                    + "sofa_modelo = '"+ sofa_modelo +"', "
                    + "sofa_cor = '"+ sofa_cor +"', "
                    + "sofa_tecido = '"+ sofa_tecido +"', "
                    + "sofa_valor = '"+ sofa_valor +"', "
                    + "sofa_tamanho = '"+ sofa_tamanho +"' "            
                    + "WHERE sofa_id = "+ sofa_id +";";
            try {stm.executeUpdate(sql);} catch (SQLException ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
            
            JOptionPane.showMessageDialog(null, "Dados alterados com sucesso");

            try { PopularJTable();} catch (Exception ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex); }
        }
        else
        {
            Connection conn = null;
            ResultSet resultadoBanco = null;
            try { conn = DBConexao.abrirConexao();} catch (Exception ex){ Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
            

            Statement stm = null;
            try { stm = conn.createStatement();} catch (SQLException ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
            String query;
            query = "INSERT INTO sofa(sofa_modelo, sofa_cor, sofa_tecido, sofa_tamanho, sofa_valor) VALUES "
                        + "('"+ sofa_modelo +"','"
                            + sofa_cor +"','"
                            + sofa_tecido +"','"
                            + sofa_tamanho +"','"
                            + sofa_valor + "');";
            try { stm.executeUpdate(query);} catch (SQLException ex) { Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}

            JOptionPane.showMessageDialog(null, "Dados cadastrados com sucesso");

            try { PopularJTable();} catch (Exception ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex); }
        }
        
        
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void txt_sofaTecidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sofaTecidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sofaTecidoActionPerformed

    private void txt_sofaValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sofaValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sofaValorActionPerformed

    private void tbview_SofaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbview_SofaMouseClicked
        // TODO add your handling code here:
        int linha = tbview_Sofa.getSelectedRow(); 
        txt_sofaId.setText(tbview_Sofa.getValueAt(linha,0).toString()); 
        txt_sofaModelo.setText(tbview_Sofa.getValueAt(linha,1).toString()); 
        txt_sofaCor.setText(tbview_Sofa.getValueAt(linha,2).toString());
        txt_sofaTecido.setText(tbview_Sofa.getValueAt(linha,3).toString()); 
        txt_sofaTamanho.setText(tbview_Sofa.getValueAt(linha,4).toString()); 
        txt_sofaValor.setText(tbview_Sofa.getValueAt(linha,5).toString()); 
    }//GEN-LAST:event_tbview_SofaMouseClicked

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        // TODO add your handling code here:
        
        String sofa_modelo = txt_sofaPesqModelo.getText();
        String sofa_cor = txt_sofaPesqCor.getText();
        
        Connection conn = null;
        ResultSet resultadoBanco = null;
        
        try { conn = DBConexao.abrirConexao();} catch (Exception ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
        Statement stm = null;     
        try {stm = conn.createStatement();} catch (SQLException ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
        
        String sql;
        String sql1 = null;
        if(!"".equals(sofa_modelo)){ sql1 = " WHERE sofa_modelo LIKE '%"+ sofa_modelo +"%' ";}
        else if(!"".equals(sofa_cor)){ sql1 = " WHERE sofa_cor LIKE '%"+ sofa_cor +"%' ";}
        else if(!"".equals(sofa_cor) && !"".equals(sofa_modelo)){ sql1 = " WHERE sofa_modelo '%"+sofa_modelo+"%' && sofa_cor LIKE '%"+ sofa_cor +"%' ";}
        else{sql1 = "";}
        sql = "SELECT * FROM sofa "
                + sql1 
                + " ;";
        try { resultadoBanco = stm.executeQuery(sql);} catch (SQLException ex) { Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
        
        DefaultTableModel model =(DefaultTableModel) tbview_Sofa.getModel();
        model.setNumRows(0);

        try 
        {
            while(resultadoBanco.next())
            {
                model.addRow(new Object[]
                {
                    //retorna os dados da tabela do BD, cada campo e um coluna.
                    resultadoBanco.getString("sofa_id"),
                    resultadoBanco.getString("sofa_modelo"),
                    resultadoBanco.getString("sofa_cor"),
                    resultadoBanco.getString("sofa_tecido"),
                    resultadoBanco.getString("sofa_tamanho"),
                    resultadoBanco.getString("sofa_valor")
                }); 
            }
        } catch (SQLException ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private void btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparActionPerformed
        // TODO add your handling code here:
        txt_sofaCor.setText("");
        txt_sofaId.setText("0");
        txt_sofaModelo.setText("");
        txt_sofaTamanho.setText("");
        txt_sofaTecido.setText("");
        txt_sofaValor.setText("");
    }//GEN-LAST:event_btn_LimparActionPerformed

    private void btn_deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletarActionPerformed
        // TODO add your handling code here:
        int linha = tbview_Sofa.getSelectedRow(); 
        String sofaId = tbview_Sofa.getValueAt(linha,0).toString();
        
        Connection conn = null;
         ResultSet resultadoBanco = null;
                     
        try {conn = DBConexao.abrirConexao();} catch (Exception ex) { Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
        Statement stm = null;
        try { stm = conn.createStatement(); } catch (SQLException ex) { Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
        
        String message = "Deseja realmente apagar o registro?";
        String title = "Confirmação";

        int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            String sql;
            sql = "DELETE FROM sofa WHERE sofa_id = " +sofaId+";";
            try { stm.executeUpdate(sql); } catch (SQLException ex) { Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}
            try { PopularJTable();} catch (Exception ex) {Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex); }
            btn_LimparActionPerformed(evt);
        }
        
        
    }//GEN-LAST:event_btn_deletarActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Form_Principal().setVisible(true);
        //Runtime.getRuntime().exit(0);
    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Sofa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Sofa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Sofa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Sofa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() { public void run() { try { new Form_Sofa().setVisible(true);} catch (Exception ex) { Logger.getLogger(Form_Sofa.class.getName()).log(Level.SEVERE, null, ex);}}});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JButton btn_deletar;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbview_Sofa;
    private javax.swing.JTextField txt_sofaCor;
    private javax.swing.JTextField txt_sofaId;
    private javax.swing.JTextField txt_sofaModelo;
    private javax.swing.JTextField txt_sofaPesqCor;
    private javax.swing.JTextField txt_sofaPesqModelo;
    private javax.swing.JTextField txt_sofaTamanho;
    private javax.swing.JTextField txt_sofaTecido;
    private javax.swing.JTextField txt_sofaValor;
    // End of variables declaration//GEN-END:variables
}
